"use strict";
exports.__esModule = true;
var Student_1 = require("./Student");
var StudentManager_1 = require("./StudentManager");
var student = new Student_1.Student('Yến', 'C08', 10, 9);
var student1 = new Student_1.Student('Yến', 'C08', 9, 10);
var student2 = new Student_1.Student('Lâm', 'C08', 8, 9);
var student3 = new Student_1.Student('Thế Anh', 'C08', 6, 8);
var student4 = new Student_1.Student('Khánh', 'C08', 2, 7);
StudentManager_1.StudentManager.add(student1);
StudentManager_1.StudentManager.add(student);
StudentManager_1.StudentManager.add(student2);
StudentManager_1.StudentManager.add(student3);
StudentManager_1.StudentManager.add(student4);
console.log(StudentManager_1.StudentManager.showList());
console.log(StudentManager_1.StudentManager.getTotalStudent());
console.log(StudentManager_1.StudentManager.showRank());
console.log(StudentManager_1.StudentManager.showRank());
console.log(StudentManager_1.StudentManager.searchByName('Yến'));
